markdown: kramdown

# Name of website
title: AI for Judges 

# Author
author: Marcello Di Bello

# theme: jekyll-theme-modernist
#remote_theme: pages-themes/dinky@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
